version: "3.6"

services:
  web:
    image: nginx:1.15.0
    ports:
      - "8000:80"
      - "25:25"
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web-net
    depends_on:
      - app

  app:
    container_name: dartionApp
    build: ""
    volumes:
      - ../dartionApp../:/dartionApp
    ports:
      - 5001:5000
    networks:
      - app-net
      - web-net
      - db-net
    depends_on:
      - db

  db:
    container_name: dartionApp-db
    image: cockroachdb/cockroach:v20.1.0
    command: start --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    environment:
      - TZ=Australia/Sydney
    volumes:
      - ./init_db.sh:/setup_db.sh
    networks:
      db-net:
        aliases:
          - db

  db2:
      container_name: dartionApp-db2
      image: cockroachdb/cockroach:v20.1.0
      command: start --insecure --join=db
      ports:
        - "26258:26257"
      environment:
        - TZ=Australia/Sydney
      depends_on:
        - db
      networks:
        db-net:
          aliases:
            - db2

networks:
    db-net:
    web-net:
      driver: bridge
    app-net:
      driver: bridge
