apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dartion-app-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: dartion-app-pv
  storageClassName: standard