apiVersion: v1
kind: PersistentVolume
metadata:
  name: dartion-app-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/darshan/data/pv"